import React from "react";
import { LayoutDashboard, Search, FolderOpen, Database, Fingerprint, Network, ShieldCheck, FileText, ListChecks, Settings, ScanLine, Users, Activity, LogOut, ClipboardCheck, Bot, Globe2 } from "lucide-react";
import type { AppView, UserRole } from "../types";

interface SidebarProps { activeView:string; onNavigate:(key:AppView|"new")=>void; role:UserRole; name?:string; onSignOut?:()=>void; }
const navByRole:Record<UserRole,{title:string;items:{key:AppView|"new";label:string;icon:any;primary?:boolean}[]}[]>={
 investigator:[
  {title:"Workspace",items:[{key:"dashboard",label:"Overview",icon:LayoutDashboard},{key:"new",label:"New Investigation",icon:Search,primary:true},{key:"active",label:"My Cases",icon:FolderOpen}]},
  {title:"Forensic Intelligence",items:[{key:"vault",label:"Evidence Vault",icon:Database},{key:"dna-network",label:"Media DNA",icon:Fingerprint},{key:"context",label:"Context Verification",icon:ShieldCheck},{key:"propagation",label:"Propagation",icon:Network},{key:"copilot",label:"Investigator Copilot",icon:Bot},{key:"osint",label:"Web OSINT",icon:Globe2}]},
  {title:"Documentation",items:[{key:"reports",label:"Forensic Reports",icon:FileText},{key:"audit",label:"Audit Trail",icon:ListChecks}]}
 ],
 "case-officer":[
  {title:"Case Review",items:[{key:"dashboard",label:"Overview",icon:LayoutDashboard},{key:"active",label:"Assigned Cases",icon:FolderOpen}]},
  {title:"Forensic Intelligence",items:[{key:"vault",label:"Evidence Vault",icon:Database},{key:"dna-network",label:"Media DNA",icon:Fingerprint},{key:"context",label:"Context Verification",icon:ShieldCheck},{key:"propagation",label:"Propagation",icon:Network},{key:"copilot",label:"Investigator Copilot",icon:Bot},{key:"osint",label:"Web OSINT",icon:Globe2}]},
  {title:"Documentation",items:[{key:"reports",label:"Forensic Reports",icon:FileText},{key:"audit",label:"Audit Trail",icon:ListChecks}]}
 ],
 admin:[
  {title:"Command",items:[{key:"dashboard",label:"Command Center",icon:LayoutDashboard},{key:"new",label:"New Investigation",icon:Search,primary:true},{key:"active",label:"All Cases",icon:FolderOpen}]},
  {title:"Forensic Intelligence",items:[{key:"vault",label:"Evidence Vault",icon:Database},{key:"dna-network",label:"Media DNA",icon:Fingerprint},{key:"context",label:"Context Verification",icon:ShieldCheck},{key:"propagation",label:"Propagation",icon:Network},{key:"copilot",label:"Investigator Copilot",icon:Bot},{key:"osint",label:"Web OSINT",icon:Globe2}]},
  {title:"Governance",items:[{key:"reports",label:"Forensic Reports",icon:FileText},{key:"audit",label:"Audit Trail",icon:ListChecks},{key:"users",label:"Users & Roles",icon:Users},{key:"settings",label:"System Settings",icon:Settings}]}
 ]
};
const roleLabel:Record<UserRole,string>={investigator:"Investigator","case-officer":"Case Officer",admin:"Administrator"};
export function Sidebar({activeView,onNavigate,role,name,onSignOut}:SidebarProps){return <aside className="flex h-screen w-[238px] shrink-0 flex-col border-r border-white/[0.07] bg-[#07101f] text-slate-300"><div className="border-b border-white/[0.07] px-3.5 py-3.5"><div className="flex items-center gap-3"><div className="brand-mark"><ScanLine size={18}/></div><div><div className="text-[13px] font-black tracking-[0.18em] text-white">TRUTHTRACE</div><div className="mt-0.5 text-[10px] text-slate-500">Digital Forensics Platform</div></div></div></div><div className="px-2.5 pt-3"><div className="role-switcher"><div className="flex items-center gap-2"><div className="role-avatar">{role==='admin'?<Users size={14}/>:role==='case-officer'?<ClipboardCheck size={14}/>:<Search size={14}/>}</div><div className="min-w-0"><div className="text-[10px] uppercase tracking-[0.14em] text-slate-500">Signed in</div><div className="truncate text-[12px] font-semibold text-white">{name||roleLabel[role]}</div><div className="text-[10px] text-blue-300">{roleLabel[role]}</div></div></div><div className="mt-3 border-t border-white/[.05] pt-2 text-[9px] uppercase tracking-[.12em] text-slate-600">Role assigned by server policy</div></div></div><nav className="flex-1 overflow-y-auto px-2.5 py-4">{navByRole[role].map(group=><div key={group.title} className="mb-5"><div className="nav-section">{group.title}</div><div className="mt-2 space-y-1">{group.items.map(item=><NavButton key={item.key} item={item} activeView={activeView} onNavigate={onNavigate}/>)}</div></div>)}</nav><div className="border-t border-white/[0.07] px-3.5 py-3.5"><div className="flex items-center justify-between rounded-lg border border-emerald-400/10 bg-emerald-400/[0.04] px-3 py-2.5"><div className="flex items-center gap-2"><span className="status-dot"/><div><div className="text-[11px] font-semibold text-slate-300">Systems operational</div><div className="text-[10px] text-slate-600">Core services online</div></div></div><Activity size={14} className="text-emerald-400/70"/></div><button onClick={onSignOut} className="mt-3 flex w-full items-center gap-2 rounded-lg px-2 py-2 text-[11px] text-slate-500 hover:bg-white/[0.04] hover:text-slate-300"><LogOut size={13}/> Sign out</button></div></aside>}
function NavButton({item,activeView,onNavigate}:any){const Icon=item.icon;const active=activeView===item.key;return <button onClick={()=>onNavigate(item.key)} className={`nav-item ${active?"nav-item-active":""} ${item.primary?"nav-primary":""}`}><Icon size={16}/><span>{item.label}</span>{item.primary&&!active&&<span className="nav-hot">START</span>}{active&&<span className="nav-active-bar"/>}</button>}
