import React,{useEffect,useState}from'react';
import{CheckCircle2,ShieldCheck,AlertCircle,Clock3,Camera,FileImage,Database,Info,AudioLines,Activity,AlertTriangle}from'lucide-react';
import{Panel,ScoreDial,SectionLabel}from'../../ui/Primitives';
import type{ToastTone}from'../../../types';
import{api}from'../../../api';
import{formatIST}from'../../../utils/dates';
const formatDate = formatIST;
function metadataValue(m:any,...keys:string[]){for(const k of keys){if(m?.[k]!==undefined&&m?.[k]!==null&&String(m[k]).trim())return String(m[k])}return null}
function pct(v:any){return v==null?'Unavailable':`${(Number(v)*100).toFixed(1)}%`}
function modelPct(v:any){return v==null?'Unavailable':`${Number(v).toFixed(1)}%`}
function detectorTone(v:any){if(v==null)return'text-slate-400';const n=Number(v);return n>=.6?'text-red-300':n<=.2?'text-emerald-300':'text-amber-300'}
export function AuthenticityTab({caseId,notify}:{caseId:string;notify:(m:string,t?:ToastTone)=>void}){
 const[d,setD]=useState<any>();const[loading,setLoading]=useState(true);
 useEffect(()=>{let on=true;setLoading(true);api.case(caseId).then(x=>{if(on)setD(x)}).catch(e=>notify(e.message,'warn')).finally(()=>on&&setLoading(false));return()=>{on=false}},[caseId]);
 if(loading||!d)return<div className="p-8 text-sm text-slate-400">Loading forensic model results…</div>;
 const isAudio=String(d.media?.mimeType||'').startsWith('audio/')||d.forensics?.kind==='audio';
 if(isAudio)return <AudioPrimary d={d}/>;
 const v=d.authenticity||{}, verdict=v.verdict||'Inconclusive', tone=verdict==='Likely Authentic'?'text-emerald-300':verdict==='Inconclusive'?'text-amber-300':'text-red-300';
 const meta=d.media?.metadata||{},capture=metadataValue(meta,'DateTimeOriginal','DateTime','creation_time','CreateDate','CreationDate'),camera=metadataValue(meta,'Make'),model=metadataValue(meta,'Model'),software=metadataValue(meta,'Software');
 const primary=v.organika||d.forensics?.models?.organika||{},secondary=v.steganographia||d.forensics?.models?.steganographia||{};
 const steps=['Evidence received','SHA-256 + perceptual fingerprint','Metadata + provenance extracted','Multi-view content-agnostic forensic inference','Evidence fusion / verdict'];
 return <div className="mx-auto max-w-5xl px-8 py-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">VERIFICATION / AUTHENTICITY</div><h2 className="mt-1 text-lg font-bold text-white">Is this media authentic?</h2><p className="text-[13px] leading-6 text-slate-400">The finding is derived from the uploaded evidence, fingerprints, metadata, multi-view forensic analysis and content-agnostic synthetic-image detectors.</p></div><div className="rounded-md border border-white/5 bg-[#091226] px-4 py-2 text-right"><div className="text-[10px] uppercase tracking-[.12em] text-slate-500">Forensic confidence</div><div className={`text-lg font-black ${tone}`}>{(Number(v.confidence||0)*100).toFixed(1)}%</div></div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[280px_1fr]"><Panel className="border-white/10 bg-[#0d1830] p-5"><SectionLabel>Verdict</SectionLabel><div className="mt-4 flex justify-center"><ScoreDial value={Math.floor(Number(v.confidence || 0) * 10000) / 100}/></div><div className={`mt-3 text-center text-sm font-bold ${tone}`}>{verdict}</div><p className="mt-3 text-center text-[11px] leading-5 text-slate-500">Confidence reflects detector evidence and agreement; it is not the same as AI-generation probability.</p></Panel><Panel className="border-white/10 bg-[#0d1830] p-5"><SectionLabel>Forensic Verification Pipeline</SectionLabel><div className="mt-3 grid gap-2">{steps.map((s,i)=><div key={s} className="flex items-center gap-3 rounded-md border border-white/5 bg-[#091226] px-3 py-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-500/10 text-[10px] font-bold text-blue-300">{i+1}</span><span className="flex-1 text-[12.5px] text-slate-300">{s}</span><CheckCircle2 size={15} className="text-emerald-400"/></div>)}</div></Panel></div>
 <Panel className="mt-5 border-white/10 bg-[#0d1830] p-5"><div className="flex items-start justify-between gap-4"><div><SectionLabel>Capture & File Metadata</SectionLabel><p className="mt-1 text-[11px] text-slate-500">Embedded metadata is reported when present. Missing EXIF data is not, by itself, evidence of manipulation.</p></div><Info size={15} className="mt-1 text-slate-500"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Meta label="Capture time" icon={<Clock3 size={13}/>} value={capture?formatDate(capture):'No embedded EXIF capture time present'}/><Meta label="Camera" icon={<Camera size={13}/>} value={`${camera||'Not available'}${model?` · ${model}`:''}`}/><Meta label="Format / MIME" icon={<FileImage size={13}/>} value={`${d.media?.fileType||'N/A'} · ${d.media?.mimeType||'N/A'}`}/><Meta label="Evidence added" icon={<Database size={13}/>} value={formatDate(d.media?.addedAt)}/></div>{software&&<div className="mt-3 rounded-md border border-white/5 bg-[#091226] px-3 py-2.5 text-[11px] text-slate-400"><span className="text-slate-500">Software tag:</span> <span className="text-slate-300">{software}</span></div>}</Panel>
 <Panel className="mt-5 border-white/10 bg-[#0d1830] p-5"><div className="flex items-center justify-between"><SectionLabel>Detector Evidence</SectionLabel><span className="text-[10px] uppercase tracking-[.12em] text-slate-500">Content-agnostic synthetic evidence</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{[{title:'Organika · primary',m:primary},{title:'SteganographIA · secondary',m:secondary}].map(({title,m})=><div key={title} className="rounded-md border border-white/5 bg-[#091226] p-4"><div className="text-[10px] uppercase tracking-[.12em] text-slate-500">{title}</div><div className="mt-1 break-all text-[11px] text-slate-400">{m.model||'Unavailable'}</div>{m.status==='disabled'?<div className="mt-5 text-xl font-black text-slate-400">Disabled</div>:m.status!=='ok'?<div className="mt-5 text-xl font-black text-red-300">Unavailable</div>:<><div className={`mt-4 text-xl font-black ${detectorTone(m.fake_probability)}`}>{pct(m.fake_probability)}</div><div className="text-[11px] text-slate-500">Fake / AI-generated</div><div className="mt-3 text-xl font-black text-emerald-300">{pct(m.real_probability)}</div><div className="text-[11px] text-slate-500">Real / authentic</div><div className="mt-3 rounded border border-white/5 bg-[#0d1830] px-3 py-2 text-[11px] text-slate-400">Prediction: <span className="font-semibold text-slate-200">{m.predicted_label||'Unknown'}</span></div></>}</div>)}</div><div className="mt-4 rounded-md border border-white/5 bg-[#091226] p-4"><div className="grid gap-3 sm:grid-cols-3"><div><span className="text-[10px] uppercase text-slate-500">Fusion</span><div className="mt-1 text-[12px] text-slate-200">{v.fusionMode||'N/A'}</div></div><div><span className="text-[10px] uppercase text-slate-500">Ensemble fake probability</span><div className={`mt-1 text-[14px] font-bold ${detectorTone(v.aiProbability!=null?Number(v.aiProbability)/100:null)}`}>{modelPct(v.aiProbability)}</div></div><div><span className="text-[10px] uppercase text-slate-500">Ensemble real probability</span><div className="mt-1 text-[14px] font-bold text-emerald-300">{modelPct(v.realProbability)}</div></div></div></div></Panel>
 <Finding v={v} verdict={verdict}/></div>
}
function AudioPrimary({d}:{d:any}){const v=d.authenticity||{},a=d.forensics?.models?.audio_detector||d.forensics?.models?.audio_baseline||{},sig=d.forensics?.signals?.audio||{},rawP=v.aiProbability??v.fakeProbability??(a.ai_probability!=null?a.ai_probability:a.synthetic_probability!=null?a.synthetic_probability*100:0),p=Number(rawP)||0;const tone=v.verdict==='Likely Authentic'?'text-emerald-300':v.verdict==='Inconclusive'?'text-amber-300':'text-red-300';return <div className="mx-auto max-w-5xl px-8 py-8"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">VERIFICATION / AUDIO AUTHENTICITY · PRIMARY</div><h2 className="mt-1 text-lg font-bold text-white">Is this audio authentic?</h2><p className="text-[13px] leading-6 text-slate-400">Audio-specific forensic results are now the primary authenticity result for this investigation.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><Panel className="border-white/10 bg-[#0d1830] p-5"><SectionLabel>Primary Verdict</SectionLabel><div className={`mt-3 text-2xl font-black ${tone}`}>{v.verdict||'Inconclusive'}</div><div className="mt-1 text-[11px] text-slate-500">{Number(v.confidence||0).toFixed(1)}% confidence</div></Panel><Panel className="border-white/10 bg-[#0d1830] p-5"><SectionLabel>Synthetic / AI probability</SectionLabel><div className="mt-3 text-2xl font-black text-blue-200">{p.toFixed(1)}%</div><div className="mt-2 h-2 rounded bg-white/5"><div className="h-2 rounded bg-blue-400" style={{width:`${Math.min(100,Math.max(0,p))}%`}}/></div></Panel><Panel className="border-white/10 bg-[#0d1830] p-5"><SectionLabel>Detector</SectionLabel><div className="mt-3 text-sm font-semibold text-white">{a.model||'Acoustic baseline'}</div><div className="mt-2 text-[11px] text-slate-500">{a.status==='ok'?'Trained model active':'Baseline / supporting signals'}</div></Panel></div><Panel className="mt-5 border-white/10 bg-[#0d1830] p-5"><div className="flex items-center gap-2"><Activity size={15} className="text-blue-300"/><SectionLabel>Audio forensic signals</SectionLabel></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{[['RMS level',sig.rms],['Zero-crossing rate',sig.zero_crossing_rate],['Spectral flatness',sig.spectral_flatness]].map(([k,x])=><div key={k as string} className="rounded-md border border-white/5 bg-[#091226] p-4"><div className="text-[10px] uppercase tracking-[.12em] text-slate-500">{k}</div><div className="mt-2 text-sm font-bold text-slate-200">{x??'—'}</div></div>)}</div></Panel><div className="mt-4 rounded-md border border-amber-400/10 bg-amber-400/[.03] p-4 text-[11px] leading-5 text-amber-200"><AlertTriangle size={13} className="mr-2 inline"/>{v.disclaimer||'Audio detection is probabilistic and should be corroborated with other evidence.'}</div></div>}
function Meta({label,icon,value}:{label:string;icon:React.ReactNode;value:string}){return <div className="rounded-md border border-white/5 bg-[#091226] p-3"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.12em] text-slate-500">{icon}{label}</div><div className="mt-2 break-words text-[12.5px] text-slate-200">{value}</div></div>}
function Finding({v,verdict}:{v:any;verdict:string}){return <Panel className="mt-5 border-white/10 bg-[#0d1830] p-5"><SectionLabel>Finding</SectionLabel><div className="mt-3 flex gap-3 rounded-md border border-white/5 bg-[#091226] p-4">{verdict==='Likely Authentic'?<ShieldCheck className="mt-0.5 shrink-0 text-emerald-400" size={17}/>:<AlertCircle className="mt-0.5 shrink-0 text-amber-400" size={17}/>}<p className="text-[13px] leading-6 text-slate-300">{v.summary||v.reason||'No finding available.'}</p></div><p className="mt-3 text-[10px] leading-5 text-slate-500">{v.disclaimer||'Model confidence is not ground truth. Review the underlying evidence.'}</p></Panel>}
