import { formatIST } from '../../../utils/dates';
import React,{useEffect,useState} from 'react';
import {ArrowRight,Clock3,ExternalLink,GitBranch,Network,ScanSearch} from 'lucide-react';
import {Panel,SectionLabel} from '../../ui/Primitives';
import {api} from '../../../api';
const fmt = formatIST;
export function PropagationTab({caseId}:{caseId:string}){
 const[d,setD]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 useEffect(()=>{api.propagation(caseId).then(setD)},[caseId]);
 const trace=async()=>{setBusy(true);setMessage('');try{const r=await api.tracePropagation(caseId);setD(r.events||[]);setMessage(`${r.created||0} stored-evidence lead(s) added.`)}catch(e:any){setMessage(e.message||'Propagation trace failed.')}finally{setBusy(false)}};
 return <div className="mx-auto max-w-5xl px-8 py-8">
  <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">FORENSIC INTELLIGENCE / PROPAGATION</div><h2 className="mt-1 text-lg font-bold text-white">Propagation Intelligence</h2><p className="max-w-3xl text-[13px] leading-6 text-slate-400">Review observed propagation events, similarity, transformations and source routes. Only stored observations are shown; the backend does not invent social-media history.</p></div><div className="flex items-center gap-3"><button onClick={trace} disabled={busy} className="inline-flex items-center gap-2 rounded-md border border-blue-400/20 bg-blue-400/10 px-3 py-2 text-[11px] font-semibold text-blue-200 disabled:opacity-50"><ScanSearch size={14}/>{busy?'Tracing…':'Trace stored evidence'}</button><GitBranch size={21} className="text-blue-300"/></div></div>
  {message&&<div className="mt-3 rounded border border-white/5 bg-[#091226] px-3 py-2 text-[11px] text-slate-400">{message}</div>}
  <Panel className="mt-5 border-white/10 bg-[#0d1830] p-5"><div className="flex items-center gap-2"><Network size={15} className="text-blue-300"/><SectionLabel>Observed Events</SectionLabel></div>{d.length?<div className="mt-4 overflow-x-auto rounded-md border border-white/5"><div className="min-w-[900px]"><div className="grid grid-cols-[190px_minmax(240px,1fr)_90px_210px] gap-4 border-b border-white/10 bg-[#091226] px-4 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500"><span>Observed (IST)</span><span>Platform / Account / Route</span><span>Similarity</span><span>Transformation</span></div>{d.map((x,i)=><div key={i} className="grid grid-cols-[190px_minmax(240px,1fr)_90px_210px] gap-4 border-b border-white/5 px-4 py-4 last:border-0"><div className="flex items-start gap-2 whitespace-nowrap text-[11px] leading-5 text-slate-300"><Clock3 size={13} className="mt-0.5 shrink-0 text-blue-300"/>{fmt(x.observed_at)}</div><div className="min-w-0 text-[12px] leading-5 text-slate-300"><div className="font-semibold text-slate-200">{x.platform||'Unknown platform'}</div><div>{x.account||'Unknown account'}</div>{(x.from_node||x.to_node)&&<div className="mt-1 flex flex-wrap items-center gap-1 text-[10px] text-slate-500"><span>{x.from_node||'Unknown source'}</span><ArrowRight size={10}/><span>{x.to_node||x.platform||'Unknown destination'}</span></div>}{x.source_url&&<div className="mt-1 flex items-start gap-1 break-all text-[10px] text-blue-300"><ExternalLink size={10} className="mt-0.5 shrink-0"/><span>{x.source_url}</span></div>}</div><div><div className="text-[13px] font-bold text-blue-200">{x.similarity}%</div><div className="mt-1 text-[10px] text-slate-500">visual similarity</div></div><div className="min-w-0 break-words text-[12px] leading-5 text-slate-300"><div>{x.transformation||'Not specified'}</div>{x.tag&&<div className="mt-1 text-[10px] uppercase tracking-[.08em] text-slate-500">{x.tag}</div>}</div></div>)}</div></div>:<div className="mt-4 rounded-md border border-white/5 bg-[#091226] p-8 text-center"><GitBranch size={22} className="mx-auto text-slate-600"/><p className="mt-3 text-sm text-slate-500">No propagation observations have been recorded for this case.</p></div>}</Panel>
  {d.length>0&&<Panel className="mt-5 border-white/10 bg-[#0d1830] p-5"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">RELATIONSHIP GRAPH</div><h3 className="mt-1 text-sm font-bold text-white">Similarity-led evidence network</h3><div className="mt-4 flex flex-wrap items-center justify-center gap-2 rounded-md border border-white/5 bg-[#091226] p-6"><div className="rounded-full border border-blue-400/30 bg-blue-400/10 px-4 py-3 text-[11px] font-bold text-blue-200">CURRENT CASE</div>{d.slice(0,8).map((x,i)=><React.Fragment key={i}><ArrowRight size={15} className="text-slate-600"/><div className="rounded-lg border border-white/10 bg-white/[.02] px-3 py-2 text-center"><div className="text-[10px] font-semibold text-slate-200">{x.to_node||x.platform||'Related evidence'}</div><div className="mt-1 text-[9px] text-blue-300">{x.similarity}% · {x.tag||'LEAD'}</div></div></React.Fragment>)}</div><p className="mt-3 text-[10px] text-slate-600">Graph edges represent stored observations or visual-similarity leads. They do not establish original source or chronology by themselves.</p></Panel>}
 </div>
}
